## Parsing given data

In [ ]:
import pandas as pd
import numpy as np

In [50]:
file = 'training_sample_by_user.tsv'
#file = 'training_sample_by_tweet.tsv'

In [3]:
column_names = ["text_tokens", "hashtags", "tweet_id", "present_media", "present_links", "present_domains",\
                "tweet_type", "language", "tweet_timestamp", "engaged_with_user_id", "engaged_with_user_follower_count",\
               "engaged_with_user_following_count", "engaged_with_user_is_verified", "engaged_with_user_account_creation",\
               "engaging_user_id", "engaging_user_follower_count", "engaging_user_following_count", "engaging_user_is_verified",\
               "engaging_user_account_creation", "engaged_follows_engaging", "reply_timestamp", "retweet_timestamp", "retweet_with_comment_timestamp", "like_timestamp"]

In [4]:
df = pd.read_csv(file, header=None, names=column_names, delimiter='\x01')

In [5]:
pd.set_option('display.max_columns', None)
print(df.shape)
display(df.head())

(80425, 24)

,text_tokens,hashtags,tweet_id,present_media,present_links,present_domains,tweet_type,language,tweet_timestamp,engaged_with_user_id,engaged_with_user_follower_count,engaged_with_user_following_count,engaged_with_user_is_verified,engaged_with_user_account_creation,engaging_user_id,engaging_user_follower_count,engaging_user_following_count,engaging_user_is_verified,engaging_user_account_creation,engaged_follows_engaging,reply_timestamp,retweet_timestamp,retweet_with_comment_timestamp,like_timestamp
0,101\t56898\t137\t174\t63247\t10526\t131\t3197\...,NaN,3C21DCFB8E3FEC1CB3D2BFB413A78220,Video,NaN,NaN,Retweet,76B8A9C3013AE6414A3E6012413CDC3B,1581467323,D1AA2C85FA644D64346EDD88470525F2,737,706,False,1403069820,000046C8606F1C3F5A7296222C88084B,131,2105,False,1573978269,False,NaN,NaN,NaN,NaN
1,101\t102463\t10230\t10105\t21040\t10169\t12811...,NaN,3D87CC3655C276F1771752081423B405,NaN,BB422AA00380E45F312FD2CAA75F4960,92D397F8E0F1E77B36B8C612C2C51E23,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1580975391,4DC65AC7BD963DE1F7617C047C33DE99,52366425,2383,True,1230139136,00006047187D0D18598EF12A650E1DAC,22,50,False,1340673962,False,NaN,NaN,NaN,NaN
2,101\t56898\t137\t11255\t22037\t10263\t168\t111...,DB32BD91C2F1B37BE700F374A07FBC61,3701848B96AA740528A2B0E247777D7D,NaN,2423BA02A75DB2189335DDC3FB6B74A1,6D323BE93766E79BE423FAC5C28BE39B,Retweet,22C448FF81263D4BAF2A176145EE9EAD,1581257232,5C671539CB41B9807E209349B101E9FF,988,167,False,1530094483,0000648BAA193AE4C625DDF789B57172,251,719,False,1456473671,False,NaN,NaN,NaN,NaN
3,101\t13073\t28757\t106\t100\t14120\t131\t120\t...,NaN,18176C6AD2871729384062F073CCE94D,Video,NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581164292,70B900BE17416923D1E236A38798F202,1228134,5413,False,1378699943,000071667F50BAFEA722A8E8284581E5,18,58,False,1378427564,False,NaN,NaN,NaN,1.581305e+09
4,101\t3460\t1923\t6632\t2824\t30368\t2179\t1881...,NaN,AF11AF01F842E7F120667B7B0B38676D,NaN,NaN,NaN,Quote,22C448FF81263D4BAF2A176145EE9EAD,1581233650,E94C0E9E8494F3D603F9D1A5C5242E3D,73,299,False,1549054499,00007745A6EE969F1A0F44B10DC17671,268,526,False,1252294800,False,NaN,NaN,NaN,NaN

Parse attributes containing tab-separated lists into lists. Transform raw timestamps into human-readable timestamps.

In [6]:
df['text_tokens'] = df['text_tokens'].str.split('\t')

def to_hex_list(x):
    output = str(x).split('\t')
#     output = [int(val, 16) for val in str(x).split('\t')] 
    return output

cols_to_process = ['hashtags', 'present_media', 'present_links', 'present_domains']

for col in cols_to_process:  
    df[col] = df[col].apply(lambda x: to_hex_list(x) if isinstance(x, str)  else x)


    
cols_to_process = ['tweet_timestamp', 'engaging_user_account_creation', 'reply_timestamp', 'retweet_timestamp', 'retweet_with_comment_timestamp', 'like_timestamp']

for col in cols_to_process:  
    df[col] = df[col].apply(lambda x: pd.Timestamp(x, unit='s'))

In [7]:
display(df.head())

,text_tokens,hashtags,tweet_id,present_media,present_links,present_domains,tweet_type,language,tweet_timestamp,engaged_with_user_id,engaged_with_user_follower_count,engaged_with_user_following_count,engaged_with_user_is_verified,engaged_with_user_account_creation,engaging_user_id,engaging_user_follower_count,engaging_user_following_count,engaging_user_is_verified,engaging_user_account_creation,engaged_follows_engaging,reply_timestamp,retweet_timestamp,retweet_with_comment_timestamp,like_timestamp
0,"[101, 56898, 137, 174, 63247, 10526, 131, 3197...",NaN,3C21DCFB8E3FEC1CB3D2BFB413A78220,[Video],NaN,NaN,Retweet,76B8A9C3013AE6414A3E6012413CDC3B,2020-02-12 00:28:43,D1AA2C85FA644D64346EDD88470525F2,737,706,False,1403069820,000046C8606F1C3F5A7296222C88084B,131,2105,False,2019-11-17 08:11:09,False,NaT,NaT,NaT,NaT
1,"[101, 102463, 10230, 10105, 21040, 10169, 1281...",NaN,3D87CC3655C276F1771752081423B405,NaN,[BB422AA00380E45F312FD2CAA75F4960],[92D397F8E0F1E77B36B8C612C2C51E23],TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,2020-02-06 07:49:51,4DC65AC7BD963DE1F7617C047C33DE99,52366425,2383,True,1230139136,00006047187D0D18598EF12A650E1DAC,22,50,False,2012-06-26 01:26:02,False,NaT,NaT,NaT,NaT
2,"[101, 56898, 137, 11255, 22037, 10263, 168, 11...",[DB32BD91C2F1B37BE700F374A07FBC61],3701848B96AA740528A2B0E247777D7D,NaN,[2423BA02A75DB2189335DDC3FB6B74A1],[6D323BE93766E79BE423FAC5C28BE39B],Retweet,22C448FF81263D4BAF2A176145EE9EAD,2020-02-09 14:07:12,5C671539CB41B9807E209349B101E9FF,988,167,False,1530094483,0000648BAA193AE4C625DDF789B57172,251,719,False,2016-02-26 08:01:11,False,NaT,NaT,NaT,NaT
3,"[101, 13073, 28757, 106, 100, 14120, 131, 120,...",NaN,18176C6AD2871729384062F073CCE94D,[Video],NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,2020-02-08 12:18:12,70B900BE17416923D1E236A38798F202,1228134,5413,False,1378699943,000071667F50BAFEA722A8E8284581E5,18,58,False,2013-09-06 00:32:44,False,NaT,NaT,NaT,2020-02-10 03:29:24
4,"[101, 3460, 1923, 6632, 2824, 30368, 2179, 188...",NaN,AF11AF01F842E7F120667B7B0B38676D,NaN,NaN,NaN,Quote,22C448FF81263D4BAF2A176145EE9EAD,2020-02-09 07:34:10,E94C0E9E8494F3D603F9D1A5C5242E3D,73,299,False,1549054499,00007745A6EE969F1A0F44B10DC17671,268,526,False,2009-09-07 03:40:00,False,NaT,NaT,NaT,NaT

## T1 - Split into train, dev, test

In [59]:
from sklearn.model_selection import train_test_split
seed = 42
X_nontest, X_test = train_test_split(df, test_size = 0.1, random_state = seed)
X_train, X_dev = train_test_split(X_nontest, test_size = 0.1, random_state = seed)
print(X_train.shape, X_dev.shape, X_test.shape)

(65143, 24) (7239, 24) (8043, 24)

## T5 - Implement a Baseline

In [8]:
from sklearn.preprocessing import MultiLabelBinarizer, OneHotEncoder
from sklearn.random_projection import GaussianRandomProjection
from sklearn.decomposition import TruncatedSVD, PCA
import scipy.sparse

Categorize the columns corresponding to their format

In [9]:
numeric_cols = ['engaged_with_user_follower_count', 
                'engaged_with_user_following_count', 
                'engaged_with_user_account_creation',
                'engaging_user_follower_count', 
                'engaging_user_following_count',
                'engaging_user_account_creation',
                'tweet_timestamp',
               ]

categorical_cols = ['tweet_type', 'language', 
                    'engaged_with_user_is_verified', 'engaging_user_is_verified', 'engaged_follows_engaging']

id_cols = ['tweet_id', 'engaged_with_user_id', 'engaging_user_id']

response_cols = ['reply_timestamp', 
                 'retweet_timestamp',
                 'retweet_with_comment_timestamp', 
                 'like_timestamp'
                ]

tweet_feature_cols = ['text_tokens', 'hashtags', 'present_media', 'present_links', 'present_domains']

In [10]:
df.columns

Index(['text_tokens', 'hashtags', 'tweet_id', 'present_media', 'present_links',
       'present_domains', 'tweet_type', 'language', 'tweet_timestamp',
       'engaged_with_user_id', 'engaged_with_user_follower_count',
       'engaged_with_user_following_count', 'engaged_with_user_is_verified',
       'engaged_with_user_account_creation', 'engaging_user_id',
       'engaging_user_follower_count', 'engaging_user_following_count',
       'engaging_user_is_verified', 'engaging_user_account_creation',
       'engaged_follows_engaging', 'reply_timestamp', 'retweet_timestamp',
       'retweet_with_comment_timestamp', 'like_timestamp'],
      dtype='object')

### Create helper functions for encoding

Helper function to encode numeric categories: 
- 'engaged_with_user_follower_count', 
- 'engaged_with_user_following_count', 
- 'engaged_with_user_account_creation', 
- 'engaging_user_follower_count', 
- 'engaging_user_following_count', 
- 'engaging_user_account_creation', 
- 'tweet_timestamp',

In [11]:
def numeric_cat(x, nq=49):
    '''
    Encodes a numeric column to categoric.

    Parameters:
        x (pd.Series): The pandas Series which shall be tranformed.
        nq (int): The number of buckets onto which the column should be distrubed.

    Returns:
        A pd.Series containing a categorical encoding of the given numeric column.
    '''
    # pd.cut and pd.qcut put NaN into bucket -1
    #might have to use cut for equal distance bins instead of equal size bins
    cat_type = pd.api.types.CategoricalDtype(categories=[*range(nq+1)], ordered=False)
    return (pd.qcut(x, nq).cat.codes + 1).astype(cat_type)

Helper function for categorical categories:
- 'tweet_type', 
- 'language', 
- 'engaged_with_user_is_verified', 
- 'engaging_user_is_verified', 
- 'engaged_follows_engaging'

In [12]:
def categorical_cat(x):
    return x.astype('category')

Helper function for id-categories:
- 'tweet_id', 
- 'engaged_with_user_id', 
- 'engaging_user_id'

In [13]:
def id_cat(x, buckets = 1000):
    return x.apply(lambda y : abs(hash(y)) % buckets).astype('category')

Helper functionn for tweet features:
- 'text_tokens', 
- 'hashtags', 
- 'present_media', 
- 'present_links', 
- 'present_domains'

In [39]:
def encode_tweetFeature(x, replacement = ['Unknown']):
    return pd.Series([replacement if y is np.nan else y for y in x])

Helper functions for response variables:
- 'reply_timestamp', 
- 'retweet_timestamp',
- 'retweet_with_comment_timestamp', 
- 'like_timestamp'

In [40]:
def encode_response(x):
    return x.notnull().astype('int8')

### Encode features using helper functions defined above

In [16]:
df[numeric_cols] = df[numeric_cols].apply(numeric_cat)
df[categorical_cols] = df[categorical_cols].apply(categorical_cat)
df[id_cols] = df[id_cols].apply(id_cat)
df[tweet_feature_cols] = df[tweet_feature_cols].apply(encode_tweetFeature)
df[response_cols] = df[response_cols].apply(encode_response)

In [17]:
df.head()

,text_tokens,hashtags,tweet_id,present_media,present_links,present_domains,tweet_type,language,tweet_timestamp,engaged_with_user_id,engaged_with_user_follower_count,engaged_with_user_following_count,engaged_with_user_is_verified,engaged_with_user_account_creation,engaging_user_id,engaging_user_follower_count,engaging_user_following_count,engaging_user_is_verified,engaging_user_account_creation,engaged_follows_engaging,reply_timestamp,retweet_timestamp,retweet_with_comment_timestamp,like_timestamp
0,"[101, 56898, 137, 174, 63247, 10526, 131, 3197...",[Unknown],113,[Video],[Unknown],[Unknown],Retweet,76B8A9C3013AE6414A3E6012413CDC3B,43,835,9,28,False,26,399,22,46,False,48,False,0,0,0,0
1,"[101, 102463, 10230, 10105, 21040, 10169, 1281...",[Unknown],582,[Unknown],[BB422AA00380E45F312FD2CAA75F4960],[92D397F8E0F1E77B36B8C612C2C51E23],TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,3,596,49,40,True,3,778,7,3,False,9,False,0,0,0,0
2,"[101, 56898, 137, 11255, 22037, 10263, 168, 11...",[DB32BD91C2F1B37BE700F374A07FBC61],291,[Unknown],[2423BA02A75DB2189335DDC3FB6B74A1],[6D323BE93766E79BE423FAC5C28BE39B],Retweet,22C448FF81263D4BAF2A176145EE9EAD,26,90,11,11,False,41,231,29,37,False,22,False,0,0,0,0
3,"[101, 13073, 28757, 106, 100, 14120, 131, 120,...",[Unknown],833,[Video],[Unknown],[Unknown],TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,18,102,44,45,False,24,212,6,4,False,13,False,0,0,0,1
4,"[101, 3460, 1923, 6632, 2824, 30368, 2179, 188...",[Unknown],375,[Unknown],[Unknown],[Unknown],Quote,22C448FF81263D4BAF2A176145EE9EAD,24,303,1,16,False,44,59,29,33,False,3,False,0,0,0,0

### Onehot encode tweet feature columns

In [18]:
tweet_feature_cols

['text_tokens',
 'hashtags',
 'present_media',
 'present_links',
 'present_domains']

In [19]:
mlb_text_tokens = MultiLabelBinarizer(sparse_output=True)
mlb_hashtags = MultiLabelBinarizer(sparse_output=True)
mlb_present_media = MultiLabelBinarizer(sparse_output=True)
mlb_present_links = MultiLabelBinarizer(sparse_output=True)
mlb_present_domains = MultiLabelBinarizer(sparse_output=True)

X_text_tokens = mlb_text_tokens.fit_transform(df.text_tokens)
X_hashtags = mlb_hashtags.fit_transform(df.hashtags)
X_present_media = mlb_present_links.fit_transform(df.present_media)
X_present_links = mlb_present_links.fit_transform(df.present_links)
X_present_domains = mlb_present_domains.fit_transform(df.present_domains)

In [20]:
X_tweet_features = scipy.sparse.hstack([X_text_tokens, X_hashtags, X_present_media,
                             X_present_links, X_present_domains])

In [21]:
X_tweet_features

<80425x92969 sparse matrix of type '<class 'numpy.int32'>'
	with 3493421 stored elements in COOrdinate format>

### Onehot encode numeric, categorical and id colums

In [22]:
numeric_oh = OneHotEncoder()
categorical_oh = OneHotEncoder()
id_oh = OneHotEncoder()

X_numeric = numeric_oh.fit_transform(df[numeric_cols])
X_categorical = categorical_oh.fit_transform(df[categorical_cols])
X_id = id_oh.fit_transform(df[id_cols])

C:\Users\Armin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Armin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

### Dimensionality reduction

In [42]:
rng = np.random.RandomState(42)
num_of_comp = 25

# use gaussian random project for dimensionality reduction
#numeric_trans = GaussianRandomProjection(n_components=16, random_state=rng)
#categorical_trans = GaussianRandomProjection(n_components=16, random_state=rng)
#id_trans = GaussianRandomProjection(n_components=16, random_state=rng)
#tweet_features_trans = GaussianRandomProjection(n_components=16, random_state=rng)

# use truncated SVD for dim. reduction
numeric_trans = TruncatedSVD(n_components=num_of_comp, random_state=rng)
categorical_trans = TruncatedSVD(n_components=num_of_comp, random_state=rng)
id_trans = TruncatedSVD(n_components=num_of_comp, random_state=rng)
tweet_features_trans = TruncatedSVD(n_components=num_of_comp, random_state=rng)

X_numeric_trans = numeric_trans.fit_transform(X_numeric)
X_categorical_trans = categorical_trans.fit_transform(X_categorical)
X_id_trans = id_trans.fit_transform(X_id)
X_tweet_features_trans = tweet_features_trans.fit_transform(X_tweet_features)

In [43]:
X_trans = np.hstack([X_numeric_trans, X_categorical_trans, X_id_trans, X_tweet_features_trans])

### Set response variable

In [45]:
y = df['like_timestamp']

In [46]:
X_trans.shape, y.shape

((80425, 100), (80425,))

### Compute Metrics

In [47]:
from sklearn.metrics import precision_recall_curve, auc, log_loss

def compute_prauc(pred, gt):
  prec, recall, thresh = precision_recall_curve(gt, pred)
  prauc = auc(recall, prec)
  return prauc

def calculate_ctr(gt):
  positive = len([x for x in gt if x == 1])
  ctr = positive/float(len(gt))
  return ctr

def compute_rce(pred, gt):
    cross_entropy = log_loss(gt, pred)
    data_ctr = calculate_ctr(gt)
    strawman_cross_entropy = log_loss(gt, [data_ctr for _ in range(len(gt))])
    return (1.0 - cross_entropy/strawman_cross_entropy)*100.0

### Build epic model

In [48]:
import keras
import tensorflow as tf

In [32]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers import LeakyReLU

# define loss functions for tf
def pr_auc(y_true, y_pred):
    return tf.py_function(compute_prauc, (y_pred, y_true), tf.float64)

#huber = tf.keras.losses.Huber()
#huber = tf.losses.Huber()
# Building the model

def generate_model():
    model = Sequential()

    model.add(Dense(128, input_shape=(64,)))
    model.add(LeakyReLU(alpha=0.1))
    model.add(Dropout(0.2))

    model.add(Dense(64))
    model.add(LeakyReLU(alpha=0.1))
    model.add(Dropout(0.2))

    model.add(Dense(32))
    model.add(LeakyReLU(alpha=0.1))
    model.add(Dropout(0.2))

    model.add(Dense(1))
    model.add(Activation('relu'))

    opt = keras.optimizers.Adam(learning_rate=0.001)
    model.compile(loss = "huber_loss", optimizer=opt, metrics=[pr_auc])
    
    #model.summary()
    
    return model

In [49]:
#print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

In [34]:
model = generate_model()
#model.summary()

WARNING:tensorflow:From C:\Users\Armin\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 128)               8320
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 128)               0
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256
_________________________________________________________________
leaky_re_lu_2 (LeakyReLU)    (None, 64)                0
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0
_________________________________________________________________
dense_3 (Dense)              (None, 32)                2080
_________________________________________________________________
leaky_re_lu_3 (LeakyReLU)    (None, 32)                0
_________________________________________________________________
dropout_3 (Dropout)          (None, 32)                0
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 33
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0
=================================================================
Total params: 18,689
Trainable params: 18,689
Non-trainable params: 0
_________________________________________________________________

### Without CV

In [36]:
# since this is all about twtr https://twitter.com/ylecun/status/989610208497360896
# 10^6 steps ~ 400 epochs of batch_size32 since we have 80k samples
model = generate_model()
model.fit(X_trans, y, epochs=10, batch_size=32, verbose=0, validation_split=0.2)

### With 10-folded CV

In [37]:
from sklearn.model_selection import StratifiedKFold

num_folds = 10
epochs = 10
batch_size = 8000

prauc_per_fold = []
loss_per_fold = []

kfold = StratifiedKFold(n_splits=num_folds, shuffle=True)

fold_no = 1
for train, test in kfold.split(X_trans, y):
    model = generate_model()
    
    print('------------------------------------------------------------------------')
    print(f'Training for fold {fold_no} ...')
    
    model.fit(X_trans[train], y[train], batch_size=batch_size,
              epochs=epochs, verbose=0)
    
    scores = model.evaluate(X_trans[test], y[test], verbose=0)
    print(f'Score for fold {fold_no}: loss of {scores[0]}; prauc of {scores[1]}')
    
    loss_per_fold.append(scores[0])
    prauc_per_fold.append(scores[1])
    
    fold_no += 1
    
print('------------------------------------------------------------------------')
print('Score per fold:')
print('Fold |  Loss  |  PRAUC')
for i in range(num_folds):
    print('%4d | %.4f | %.4f' % (i+1, loss_per_fold[i], prauc_per_fold[i]))
print('------------------------------------------------------------------------')
print('Average scores for all folds:')
print('        mean  +- std')
print('PRAUC: %.4f +- %.4f' % (np.mean(prauc_per_fold), np.std(prauc_per_fold)))
print('Loss:  %.4f +- %.4f' % (np.mean(loss_per_fold), np.std(loss_per_fold)))
print('------------------------------------------------------------------------')

------------------------------------------------------------------------
Training for fold 1 ...
Score for fold 1: loss of 0.11244310408993659; prauc of 0.7306671738624573
------------------------------------------------------------------------
Training for fold 2 ...
Score for fold 2: loss of 0.11308447414224626; prauc of 0.7331075072288513
------------------------------------------------------------------------
Training for fold 3 ...
Score for fold 3: loss of 0.11008058491148018; prauc of 0.7261859774589539
------------------------------------------------------------------------
Training for fold 4 ...
Score for fold 4: loss of 0.1158717483063445; prauc of 0.7315766215324402
------------------------------------------------------------------------
Training for fold 5 ...
Score for fold 5: loss of 0.1095748707203686; prauc of 0.7349787354469299
------------------------------------------------------------------------
Training for fold 6 ...
Score for fold 6: loss of 0.11250497828784554; prauc of 0.7171033024787903
------------------------------------------------------------------------
Training for fold 7 ...
Score for fold 7: loss of 0.11197373752376387; prauc of 0.7186763286590576
------------------------------------------------------------------------
Training for fold 8 ...
Score for fold 8: loss of 0.1142888586857935; prauc of 0.7236385941505432
------------------------------------------------------------------------
Training for fold 9 ...
Score for fold 9: loss of 0.11299284667821702; prauc of 0.7248297929763794
------------------------------------------------------------------------
Training for fold 10 ...
Score for fold 10: loss of 0.11061883574544835; prauc of 0.730293869972229
------------------------------------------------------------------------
Score per fold:
Fold |  Loss  |  PRAUC
   1 | 0.1124 | 0.7307
   2 | 0.1131 | 0.7331
   3 | 0.1101 | 0.7262
   4 | 0.1159 | 0.7316
   5 | 0.1096 | 0.7350
   6 | 0.1125 | 0.7171
   7 | 0.1120 | 0.7187
   8 | 0.1143 | 0.7236
   9 | 0.1130 | 0.7248
  10 | 0.1106 | 0.7303
------------------------------------------------------------------------
Average scores for all folds:
        mean  +- std
PRAUC: 0.7271 +- 0.0057
Loss:  0.1123 +- 0.0018
------------------------------------------------------------------------