In [30]:
import pandas as pd
import numpy as np

In [31]:
file = 'training_sample_by_user.tsv'
#file = 'training_sample_by_tweet.tsv'

In [32]:
column_names = ["text_tokens", "hashtags", "tweet_id", "present_media", "present_links", "present_domains",\
                "tweet_type", "language", "tweet_timestamp", "engaged_with_user_id", "engaged_with_user_follower_count",\
               "engaged_with_user_following_count", "engaged_with_user_is_verified", "engaged_with_user_account_creation",\
               "engaging_user_id", "engaging_user_follower_count", "engaging_user_following_count", "engaging_user_is_verified",\
               "engaging_user_account_creation", "engaged_follows_engaging", "reply_timestamp", "retweet_timestamp", "retweet_with_comment_timestamp", "like_timestamp"]

In [33]:
df = pd.read_csv(file, header=None, names=column_names, delimiter='\x01')

In [34]:
pd.set_option('display.max_columns', None)
print(df.shape)
display(df.head())

(80425, 24)

,text_tokens,hashtags,tweet_id,present_media,present_links,present_domains,tweet_type,language,tweet_timestamp,engaged_with_user_id,engaged_with_user_follower_count,engaged_with_user_following_count,engaged_with_user_is_verified,engaged_with_user_account_creation,engaging_user_id,engaging_user_follower_count,engaging_user_following_count,engaging_user_is_verified,engaging_user_account_creation,engaged_follows_engaging,reply_timestamp,retweet_timestamp,retweet_with_comment_timestamp,like_timestamp
0,101\t56898\t137\t174\t63247\t10526\t131\t3197\...,NaN,3C21DCFB8E3FEC1CB3D2BFB413A78220,Video,NaN,NaN,Retweet,76B8A9C3013AE6414A3E6012413CDC3B,1581467323,D1AA2C85FA644D64346EDD88470525F2,737,706,False,1403069820,000046C8606F1C3F5A7296222C88084B,131,2105,False,1573978269,False,NaN,NaN,NaN,NaN
1,101\t102463\t10230\t10105\t21040\t10169\t12811...,NaN,3D87CC3655C276F1771752081423B405,NaN,BB422AA00380E45F312FD2CAA75F4960,92D397F8E0F1E77B36B8C612C2C51E23,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1580975391,4DC65AC7BD963DE1F7617C047C33DE99,52366425,2383,True,1230139136,00006047187D0D18598EF12A650E1DAC,22,50,False,1340673962,False,NaN,NaN,NaN,NaN
2,101\t56898\t137\t11255\t22037\t10263\t168\t111...,DB32BD91C2F1B37BE700F374A07FBC61,3701848B96AA740528A2B0E247777D7D,NaN,2423BA02A75DB2189335DDC3FB6B74A1,6D323BE93766E79BE423FAC5C28BE39B,Retweet,22C448FF81263D4BAF2A176145EE9EAD,1581257232,5C671539CB41B9807E209349B101E9FF,988,167,False,1530094483,0000648BAA193AE4C625DDF789B57172,251,719,False,1456473671,False,NaN,NaN,NaN,NaN
3,101\t13073\t28757\t106\t100\t14120\t131\t120\t...,NaN,18176C6AD2871729384062F073CCE94D,Video,NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581164292,70B900BE17416923D1E236A38798F202,1228134,5413,False,1378699943,000071667F50BAFEA722A8E8284581E5,18,58,False,1378427564,False,NaN,NaN,NaN,1.581305e+09
4,101\t3460\t1923\t6632\t2824\t30368\t2179\t1881...,NaN,AF11AF01F842E7F120667B7B0B38676D,NaN,NaN,NaN,Quote,22C448FF81263D4BAF2A176145EE9EAD,1581233650,E94C0E9E8494F3D603F9D1A5C5242E3D,73,299,False,1549054499,00007745A6EE969F1A0F44B10DC17671,268,526,False,1252294800,False,NaN,NaN,NaN,NaN

Parse attributes containing tab-separated lists into lists. Transform raw timestamps into human-readable timestamps.

In [35]:
df['text_tokens'] = df['text_tokens'].str.split('\t')

def to_hex_list(x):
    output = str(x).split('\t')
#     output = [int(val, 16) for val in str(x).split('\t')] 
    return output

cols_to_process = ['hashtags', 'present_media', 'present_links', 'present_domains']

for col in cols_to_process:  
    df[col] = df[col].apply(lambda x: to_hex_list(x) if isinstance(x, str)  else x)


    
cols_to_process = ['tweet_timestamp', 'engaging_user_account_creation', 'reply_timestamp', 'retweet_timestamp', 'retweet_with_comment_timestamp', 'like_timestamp']

for col in cols_to_process:  
    df[col] = df[col].apply(lambda x: pd.Timestamp(x, unit='s'))

In [36]:
display(df.head())

,text_tokens,hashtags,tweet_id,present_media,present_links,present_domains,tweet_type,language,tweet_timestamp,engaged_with_user_id,engaged_with_user_follower_count,engaged_with_user_following_count,engaged_with_user_is_verified,engaged_with_user_account_creation,engaging_user_id,engaging_user_follower_count,engaging_user_following_count,engaging_user_is_verified,engaging_user_account_creation,engaged_follows_engaging,reply_timestamp,retweet_timestamp,retweet_with_comment_timestamp,like_timestamp
0,"[101, 56898, 137, 174, 63247, 10526, 131, 3197...",NaN,3C21DCFB8E3FEC1CB3D2BFB413A78220,[Video],NaN,NaN,Retweet,76B8A9C3013AE6414A3E6012413CDC3B,2020-02-12 00:28:43,D1AA2C85FA644D64346EDD88470525F2,737,706,False,1403069820,000046C8606F1C3F5A7296222C88084B,131,2105,False,2019-11-17 08:11:09,False,NaT,NaT,NaT,NaT
1,"[101, 102463, 10230, 10105, 21040, 10169, 1281...",NaN,3D87CC3655C276F1771752081423B405,NaN,[BB422AA00380E45F312FD2CAA75F4960],[92D397F8E0F1E77B36B8C612C2C51E23],TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,2020-02-06 07:49:51,4DC65AC7BD963DE1F7617C047C33DE99,52366425,2383,True,1230139136,00006047187D0D18598EF12A650E1DAC,22,50,False,2012-06-26 01:26:02,False,NaT,NaT,NaT,NaT
2,"[101, 56898, 137, 11255, 22037, 10263, 168, 11...",[DB32BD91C2F1B37BE700F374A07FBC61],3701848B96AA740528A2B0E247777D7D,NaN,[2423BA02A75DB2189335DDC3FB6B74A1],[6D323BE93766E79BE423FAC5C28BE39B],Retweet,22C448FF81263D4BAF2A176145EE9EAD,2020-02-09 14:07:12,5C671539CB41B9807E209349B101E9FF,988,167,False,1530094483,0000648BAA193AE4C625DDF789B57172,251,719,False,2016-02-26 08:01:11,False,NaT,NaT,NaT,NaT
3,"[101, 13073, 28757, 106, 100, 14120, 131, 120,...",NaN,18176C6AD2871729384062F073CCE94D,[Video],NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,2020-02-08 12:18:12,70B900BE17416923D1E236A38798F202,1228134,5413,False,1378699943,000071667F50BAFEA722A8E8284581E5,18,58,False,2013-09-06 00:32:44,False,NaT,NaT,NaT,2020-02-10 03:29:24
4,"[101, 3460, 1923, 6632, 2824, 30368, 2179, 188...",NaN,AF11AF01F842E7F120667B7B0B38676D,NaN,NaN,NaN,Quote,22C448FF81263D4BAF2A176145EE9EAD,2020-02-09 07:34:10,E94C0E9E8494F3D603F9D1A5C5242E3D,73,299,False,1549054499,00007745A6EE969F1A0F44B10DC17671,268,526,False,2009-09-07 03:40:00,False,NaT,NaT,NaT,NaT

## T1 - Split into train, dev, test

In [20]:
from sklearn.model_selection import train_test_split
seed = 42
X_nontest, X_test = train_test_split(df, test_size = 0.1, random_state = seed)
X_train, X_dev = train_test_split(X_nontest, test_size = 0.1, random_state = seed)
print(X_train.shape, X_dev.shape, X_test.shape)

(65143, 24) (7239, 24) (8043, 24)

## T2 - Evaluation

In [21]:
def has_timestamp(x):
  return int(not pd.isnull(x))

def create_labels(col):
  copy_test = X_test.copy()
  copy_test['label'] = copy_test.apply(lambda row: has_timestamp(row[col]), axis = 1)
  return copy_test[['engaging_user_id', 'tweet_id', 'label']]

def write_groundtruth(engagement):
  gt = create_labels(engagement + '_timestamp')
  gt.to_csv('gt_' + engagement + '.csv', index = False)
    
def read_predictions(file):
  return pd.read_csv(file, names = ['user_id', 'tweet_id', 'label'], header = 0)

write_groundtruth('reply')
write_groundtruth('retweet')
write_groundtruth('retweet_with_comment')
write_groundtruth('like')

## T3 - Create a Ratings Matrix

In [22]:
from scipy import sparse as sp

In [23]:
unique_user_ids = df['engaging_user_id'].append(df['engaged_with_user_id']).unique()
unique_user_ids.sort()

unique_tweet_ids = df['tweet_id'].unique()
unique_tweet_ids.sort()

m = len(unique_user_ids)
n = len(unique_tweet_ids)

userId_to_userIDX = dict(zip(unique_user_ids, range(m)))
userIDX_to_userId = dict(zip(range(m), unique_user_ids))

tweetId_to_tweetIDX = dict(zip(unique_tweet_ids, range(n)))
tweetIDX_to_tweetId = dict(zip(range(n), unique_tweet_ids))

In [24]:
cols = ['tweet_id', 'engaging_user_id', 'reply_timestamp', 'retweet_timestamp',
       'retweet_with_comment_timestamp', 'like_timestamp']

r_df = pd.concat([df['engaging_user_id'].map(userId_to_userIDX),
                  df['tweet_id'].map(tweetId_to_tweetIDX),
                  df['reply_timestamp'].notnull(),
                  df['retweet_timestamp'].notnull(),
                  df['retweet_with_comment_timestamp'].notnull(),
                  df['like_timestamp'].notnull()], axis = 1)

r_df.columns = ['user', 'tweet', 'reply', 'retweet', 'retweet_wc', 'like']
r_df.sort_values(['user', 'tweet'], inplace = True)

r_df.head(n = 20)

       user  tweet  reply  retweet  retweet_wc   like
0         2  18571  False    False       False  False
49179     2  28569  False    False       False  False
17919     2  30585  False    False       False  False
14877     2  62097  False    False       False  False
14878     3   4907  False    False       False  False
24129     3   6711  False    False       False  False
1         3  18974  False    False       False  False
61694     3  40982  False    False       False  False
42968     3  52605  False    False       False  False
11699     3  69266  False    False       False   True
2         4  17008  False    False       False  False
74105     4  18144  False    False       False  False
61695     4  20513  False    False       False   True
27347     4  63056   True    False       False   True
3         5   7394  False    False       False   True
39825     5   7736  False    False       False  False
24130     5  17550  False    False       False  False
11700     5  27676  False    False       False  False
55413     5  37086  False    False       False  False
71027     5  48143  False    False       False  False

In [25]:
R_reply = sp.csr_matrix((r_df.reply.astype('int8') * 2 -1, (r_df.user, r_df.tweet)), 
                        shape=(m, n))

R_retweet = sp.csr_matrix((r_df.retweet.astype('int8') * 2 -1, (r_df.user, r_df.tweet)), 
                          shape=(m, n))

R_retweet_wc = sp.csr_matrix((r_df.retweet_wc.astype('int8') * 2 -1, (r_df.user, r_df.tweet)), 
                             shape=(m, n))

R_like = sp.csr_matrix((r_df.like.astype('int8') * 2 -1, (r_df.user, r_df.tweet)), 
                       shape=(m, n))

display(R_reply.shape)
display(R_retweet.shape)
display(R_retweet_wc.shape)
display(R_like.shape)

(65963, 78795)

(65963, 78795)

(65963, 78795)

(65963, 78795)

## User-user collaborative filtering

The following code computes the average rating of each user.

In [ ]:
user_sums = R_like.sum(axis=1).A1 ## matrix converted to 1-D array via .A1
user_avgs = user_sums / n # devide through total number of tweets to get percentage of interaction
print("R_like", R_like)
print("user_sums[4]", user_sums[4])
print("user_avgs[4]", user_avgs[4])

### User-User Similarity (Not needed - Just for Debugging)

The following function computes the mean-centered cosine similarity between two users.

In [ ]:
from scipy.sparse.linalg import norm

def compute_pairwise_user_similarity(u_id, v_id):
    u = R_like[u_id,:].copy()
    v = R_like[v_id,:].copy()
    
    numerator_matrix = u.dot(v.T)
    numerator = numerator_matrix[0,0]

    denominator = norm(u) * norm(v)
    
    if denominator == 0:
        similarity = 0.;
    else:
        similarity = numerator/denominator
    
    return similarity

In [ ]:
# TEST
display(compute_pairwise_user_similarity(4, 6))

### User to all Users Similarities

The following function computes the cosine similarities of a given user to all other users.

In [26]:
import sklearn.preprocessing as pp

def compute_user_similarities(u_id):
    uU = np.empty((m,))

    R_avg = np.asmatrix(user_avgs).transpose()
    R_avg = sp.diags(user_avgs)

    R_avg = R_avg * R_like.astype(bool).astype(int)
    R_like_copy = R_like - R_avg
    pp.normalize(R_like_copy, copy=False)
    u = R_like_copy[u_id,:]
    uU = R_like_copy.dot(u.T)
    
    return uU.toarray().flatten()

In [27]:
# TEST
uU = compute_user_similarities(11321)
print("uU", uU)
print("Most relevant Users:",np.argsort(uU)[::-1])
print("Most relevance:",uU[np.argsort(uU)[::-1]])

NameError: name 'user_avgs' is not defined

### Create User Neighborhood

The following function creates the user neighborhood of a given user. It takes as input, the target user u_id and the target itemi_id, and uses additional parameters, the size k of the neighborhood.

In [ ]:
R_like_dok = R_like.todok()

## default values
k = 5

def create_user_neighborhood(u_id, i_id):
    nh = {} ## the neighborhood dict with (user id: similarity) entries
    ## nh should not contain u_id and only include users that have interacted with i_id; there should be at most k neighbors
    uU = compute_user_similarities(u_id)
    uU_copy = uU.copy() ## so that we can modify it, but also keep the original

    uU_sort = np.argsort(uU_copy)[::-1]
        
    i = 0
    while len(nh) < k and i < len(uU_sort):
        if uU_sort[i] != u_id and (uU_sort[i], i_id) in R_like_dok:
            nh[uU_sort[i]] = uU[uU_sort[i]].item(0)
        i += 1

    return nh

In [ ]:
# TEST
k = 5

nh = create_user_neighborhood(4, 6)
display(nh)

### Predict a Probability (internal_ids)

In [28]:
def predict_rating_internal(u_id, i_id):

    if (u_id, i_id) in R_like_dok:
        print("user", u_id, "has interacted on item", i_id, "with", R_like_dok[u_id, i_id])
    else:
        print("user", u_id, "has not interacted with item", i_id)
        print("k:", k)


    nh = create_user_neighborhood(u_id, i_id)

    neighborhood_weighted_avg = 0.
    numerator = 0.
    denominator = 0.

    for v in nh:
        numerator += nh[v] * R_like[v,i_id]

        denominator += np.absolute(nh[v])


    if denominator == 0:
        neighborhood_weighted_avg = 0.;
    else:
        neighborhood_weighted_avg = numerator/denominator


    prediction = neighborhood_weighted_avg
    print(f'prediction {prediction:.4f} (user_avg {user_avgs[u_id]:.4f})')
    print("")
    return prediction

In [ ]:
# TEST
k = 50
predict_rating_internal(11321, 933)

### Predict a Probability (External IDs)

In [ ]:
def predict_rating(engaging_user_id, tweet_id):
    print("user", engaging_user_id, "has internal id ", userId_to_userIDX[engaging_user_id])
    print("tweet", tweet_id, "has internal id ", tweetId_to_tweetIDX[tweet_id])
    return predict_rating_internal(userId_to_userIDX[engaging_user_id],tweetId_to_tweetIDX[tweet_id])

In [ ]:
# TEST
k = 50
predict_rating("00007745A6EE969F1A0F44B10DC17671", "3701848B96AA740528A2B0E247777D7D")
%time predict_rating("5C671539CB41B9807E209349B101E9FF", "18176C6AD2871729384062F073CCE94D")

print("done!")